name: demo_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tomatoes_stage1.png
    - assets/tomatoes_stage2.png
    - assets/tomatoes_stage3.png
    - assets/potatoes_stage1.png
    - assets/potatoes_stage2.png
    - assets/potatoes_stage3.png
    - assets/carrots_stage1.png
    - assets/carrots_stage2.png
    - assets/carrots_stage3.png
    - assets/pixel_field.png
    - assets/background.png
    - assets/background_music.mp3
    - assets/watering_can.png
    - assets/basic_fertilizer.png

  fonts:
    - family: Pixel
      fonts:
        - asset: assets/Minecraft.ttf
